function guihelp

screen_resolution = get(0, 'ScreenSize');
screen_width = screen_resolution(3);
screen_height = screen_resolution(4);
 
window_width = 427;
window_height = 525;
 
window_position = [(screen_width/2 - window_width/2),...
 (screen_height/2 - window_height/2),...
 window_width,...
 window_height];
 
main = figure('Name','HELP',...
 'NumberTitle','off',...
 'Resize','off',...
 'Visible','on',...
 'MenuBar', 'none',...
 'DoubleBuffer', 'on',...
 'units', 'pixels',...
 'color', [.9 .9 .9],...
 'Position', window_position); 

panel1 = uipanel('Parent', main, 'Units', 'pixels', 'Visible', 'on', 'Position', [5 5 420 515]);

pomoc = sprintf(['Interface aplikacji zostal podzielony na trzy sekcje.\n\n'...
    'I sekcja:\nWybor sygnalu testowego, definiowanie wejsciowej i wyjsciowej szybkosci probkownaia.\nSkrypt wylicza krotnosci L i M oraz czêstotliwoœæ, do której s¹ przenoszone sk³adowe sygna³u wejœciowego (Fmax).\n'...
    ' UWAGA! Czêstotliwoœæ Fmax wyznacza pocz¹tek pasma zaporowego filtru interpolacyjnego dla realizacji jednostopniowej\n\n'...
    'II sekcja:\nDefiniowanie liczby stopni oraz krotnosci poszczegolnych stopni\n'...
    ' UWAGA! Iloczyn wszystkich Li(Mi) musi byæ równy L(M)\nDolna i gorna granice pasma przejsciowego moze definiowac uzytkownik lub skorzystac z wyliczenia wartosci przez skrypt, ktore nastepnie moze edytowac.\n\n'...
    'III sekcja:\nPrzycisk uruchomienia zmiany szybkosci probkowania.\nWynikiem dzialania skryptu jest wyswietlenie liczby wspolczynnikow dla filtrow kazdego ze stopni oraz wykresow.\n'...
    ' UWAGA! Wyœwietlana wartoœæ czêstotliwoœci Fmax jest wyró¿niana na czerwono je¿eli dla danej implementacji wielostopniowej jest ona mniejsza wartoœci mo¿liwej do uzyskania w implementacji jednostopniowej (wartoœæ wyœwietlana w sekcji I).']);

uicontrol('Parent', panel1, 'Style', 'text', 'String', pomoc, 'Position', [10 10 395 490], 'FontName', 'Times New Roman CE', 'FontSize', 10, 'HorizontalAlignment', 'left');

end